### ISSUE TITLE
Pressure calibration for PROFFASTpylot

### ISSUE THREAD

**Issue by cfleur** [tum-esm/em27-retrieval-pipeline#114]
I noticed that pressure calibration was removed from the metadata for exports here: https://github.com/tum-esm/em27-retrieval-pipeline/issues/60.

Is there a way to provide a pressure factor (pressure_factor) or pressure offset (pressure_offset) to the log_type_pressure.yml file that PROFFASTpylot uses?

**Comment by dostuffthatmatters** [comment]
Hi @cfleur,

thank you for the feedback. I removed the whole calibration part from the metadata because I noticed that the topic of calibrating data is very specific to every lab – hence it is not wise to propose a generally applicable method there yet.

But, I will add these values to the config so one can pass them directly to the Pylot if needed.

**Comment by dostuffthatmatters** [comment]
The new version 1.5 supports this now :)
